# Generated by Django 6.0.2 on 2026-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=100)),
                ('ownership', models.CharField(choices=[('Company Items', 'Company Items'), ('Personal/Other', 'Personal / Other')], max_length=50)),
                ('department', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('items', models.TextField()),
                ('vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
