# Generated by Django 6.0.2 on 2026-04-21 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='IT E', max_length=100)),
                ('UserNumber', models.PositiveIntegerField()),
                ('Suspended', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Code', models.PositiveIntegerField()),
                ('Action', models.TextField(max_length=50)),
                ('Comment', models.TextField(max_length=100)),
                ('Summary', models.TextField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
